- name: Copy containerd-install.sh
  ansible.builtin.copy:
    src: containerd-install.sh
    dest: /root/containerd-install.sh
    mode: "755"
    owner: root
    group: root
  register: containerd_install_copy

- name: Copy containerd sha256sum
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /root/
    mode: "644"
    owner: root
    group: root
  with_fileglob: "sha256sum/*"
  register: sha256sum_copy

- name: Copy config.toml
  ansible.builtin.copy:
    src: "config.toml"
    dest: /etc/containerd/
    mode: "644"
    owner: root
    group: root
  register: configtoml_copy

- name: Containerd installation
  ansible.builtin.command: /root/containerd-install.sh
  when: containerd_install_copy.changed or sha256sum_copy.changed or configtoml_copy.changed
  changed_when: containerd_install_copy.changed or sha256sum_copy.changed or configtoml_copy.changed
