apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/carlosgit2016/homelab.git
    path: manifests/jackett
    targetRevision: main
    directory:
     recurse: false
     include: '*.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: jackett

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
