apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/carlosgit2016/homelab.git
      targetRevision: HEAD
      ref: valuesRepo

    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: "66.2.1"
      chart: prometheus-community/kube-prometheus-stack
      helm:
        valueFiles:
          - $valuesRepo/manifests/prometheus/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jackett

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
