apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/carlosgit2016/homelab.git
      targetRevision: HEADlonghorn
      ref: valuesRepo

    - repoURL: https://charts.longhorn.io
      targetRevision: "1.7.1"
      chart: longhorn
      helm:
        valueFiles:
          - $valuesRepo/manifests/longhorn/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
