apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/carlosgit2016/homelab.git
      targetRevision: HEAD
      ref: valuesRepo

    - repoURL: https://kubernetes-sigs.github.io/metrics-server
      targetRevision: "3.12.2"
      chart: metrics-server
      helm:
        valueFiles:
          - $valuesRepo/manifests/metrics-server/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
