apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/carlosgit2016/homelab.git
      targetRevision: HEAD
      ref: valuesRepo

    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: "4.14.3"
      chart: ingress-nginx
      helm:
        valueFiles:
          - $valuesRepo/manifests/nginx/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress-controller

  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
