apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/carlosgit2016/homelab.git
      targetRevision: HEAD
      ref: valuesRepo

    - repoURL: https://github.com/bitnami/charts.git
      targetRevision: "nginx-ingress-controller/11.6.0"
      path: bitnami/nginx-ingress-controller
      helm:
        valueFiles:
          - $valuesRepo/manifests/nginx/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress-controller

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
