apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/carlosgit2016/homelab.git
    path: manifests/qbittorrent
    targetRevision: HEAD
    directory:
     recurse: false
     include: '*.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: radarr

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
