apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/carlosgit2016/homelab.git
    path: manifests/rbac
    targetRevision: HEAD
    directory:
     recurse: false
     include: '*.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: rbac

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
