- name: Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: Common packages install
  ansible.builtin.apt:
    pkg:
      - vim
      - net-tools
      - netcat-traditional
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - telnet
      - python3-yaml
      - python3-kubernetes
    state: latest

- name: Configure public key to root
  ansible.builtin.copy:
    src: files/authorized_keys
    dest: /root/.ssh/authorized_keys
    mode: "640"

- name: Configure public key to cflor
  ansible.builtin.copy:
    src: files/authorized_keys
    dest: /home/cflor/.ssh/authorized_keys
    mode: "640"

- name: Checking swap status
  ansible.builtin.command: swapon --show
  register: swapon_output
  changed_when: false

- name: Disable swap
  ansible.builtin.shell: |
    dphys-swapfile swapoff
    dphys-swapfile uninstall
    systemctl stop dphys-swapfile.service
    systemctl disable dphys-swapfile.service
    systemctl mask dphys-swapfile.service
  args:
    executable: /bin/bash
  changed_when: swapon_output.stdout != ""
