apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  avoidBuggyIPs: true
  addresses:
  - 192.168.1.20/32
  - 192.168.1.21/32
  - 192.168.1.22/32
  - 192.168.1.23/32
  - 192.168.1.24/32
