- name: Copy kubeadm ClusterConfiguration
  ansible.builtin.copy:
    src: kubeadm-clusterconfig.yaml
    dest: /root/kubeadm-clusterconfig.yaml
    mode: "0644"
  register: cluster_config_copy

- name: Cluster init
  ansible.builtin.command: >-
    kubeadm init
    --config=/root/kubeadm-clusterconfig.yaml
    --ignore-preflight-errors=all
  changed_when: cluster_config_copy.changed
  register: cluster_init

- name: Kubectl admin configuration
  ansible.builtin.shell: |
    set -e
    echo "export KUBECONFIG=/etc/kubernetes/admin.conf" >> /home/cflor/.bashrc
    echo "export KUBECONFIG=/etc/kubernetes/admin.conf" >> /root/.bashrc

    chmod 640 /etc/kubernetes/admin.conf
    chown :sudo /etc/kubernetes/admin.conf
  changed_when: cluster_init.changed
