- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Install Helm
  ansible.builtin.shell: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm

- name: Install Helm diff plugin # To improve idempotency in helm charts installation
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present
