- name: Helm package install
  ansible.builtin.apt:
    pkg: helm
    state: latest
    update_cache: true

- name: Install Helm diff plugin # To improve idempotency in helm charts installation
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present
