- name: Add apt helm key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
    id: 294AC4827C1A168A
    keyring: /etc/apt/keyrings/helm.gpg

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main"
    state: present

- name: Helm package install
  ansible.builtin.apt:
    pkg: helm
    state: latest
    update_cache: true

- name: Install Helm diff plugin # To improve idempotency in helm charts installation
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present
