apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.1 # For Helm, this refers to the chart version.

    chart: ingress-nginx  # Set this when pulling directly from a Helm repo. DO NOT set for git-hosted Helm charts.
    helm:
      releaseName: ingress-nginx

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
