- name: Control plane configuration
  hosts: controlplane
  become: true
  environment:
    CONTAINERD_VERSION: "1.7.17"
    RUNC_VERSION: "1.1.12"
    CNI_PLUGIN_VERSION: "1.4.1"
  vars:
    crictl_version: "1.30.0"
    kubernetes_version: "1.30"
  roles:
    - common
    - containerd
    - crictl
    - k8stools
    - controlplane
  tasks:
    - name: Tools configuration
      ansible.builtin.include_tasks: roles/controlplane/tasks/tools.yaml

- name: Configuring CNI
  hosts: controlplane
  become: true
  gather_facts: false
  vars:
    calico_version: "3.28.0"
  tasks:
    - name: Cni installation
      ansible.builtin.include_tasks: roles/controlplane/tasks/cni.yaml

- name: Removing taints # K8s add No Schedule taints to the control plane node on purpose for sec reasons
  hosts: controlplane
  become: true
  gather_facts: false
  tasks:
    - name: Removing taints from leonov node
      kubernetes.core.k8s_taint:
        state: absent
        name: leonov
        taints:
          - effect: NoSchedule
            key: "node-role.kubernetes.io/control-plane"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ context }}"
      changed_when: false
