- name: Control plane configuration
  hosts: controlplane
  become: true
  environment:
    CONTAINERD_VERSION: "2.0.0"
    RUNC_VERSION: "1.2.2"
    CNI_PLUGIN_VERSION: "1.6.0"
  vars:
    crictl_version: "1.31.1"
    kubernetes_version: "1.31"
  roles:
    - sourcesupdate
    - common
    - containerd
    - crictl
    - k8stools
    - controlplane
  tasks:
    - name: Tools configuration
      ansible.builtin.include_tasks: roles/controlplane/tasks/tools.yaml

- name: Configuring CNI
  hosts: controlplane
  become: true
  gather_facts: false
  vars:
    calico_version: "3.29.0"
  tasks:
    - name: Cni installation
      ansible.builtin.include_tasks: roles/controlplane/tasks/cni.yaml

- name: Removing taints # K8s add No Schedule taints to the control plane node on purpose for sec reasons
  hosts: controlplane
  become: true
  gather_facts: false
  tasks:
    - name: Removing taints from vengeance node
      kubernetes.core.k8s_taint:
        state: absent
        name: vengeance
        taints:
          - effect: NoSchedule
            key: "node-role.kubernetes.io/control-plane"
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ context }}"
      changed_when: false
