---
- name: Info
  hosts: all
  remote_user: root
  tasks:
    - name: Info
      ansible.builtin.command: nc 127.0.0.1 6443 -v
      register: info
      changed_when: true
    - name: Show info
      ansible.builtin.debug:
        var: info.stdout_lines
