- name: Node configuration
  hosts: nodes
  become: true
  environment:
    CONTAINERD_VERSION: "2.0.0"
    RUNC_VERSION: "1.2.2"
    CNI_PLUGIN_VERSION: "1.6.0"
  vars:
    crictl_version: "1.31.1"
    kubernetes_version: "1.31"
  roles:
    - sourcesupdate
    - common
    - containerd
    - crictl
    - k8stools

- name: Join cluster
  hosts: all
  gather_facts: true
  become: true
  roles:
    - joincluster
