- name: Common
  hosts: all
  remote_user: root
  strategy: free
  roles:
    - role: common

- name: Containerd Installation
  hosts: all
  remote_user: root
  strategy: free
  environment:
    CONTAINERD_VERSION: "1.7.17"
    RUNC_VERSION: "1.1.12"
    CNI_PLUGIN_VERSION: "1.4.1"
  tasks:
    - name: Containerd installation
      ansible.builtin.include_tasks: roles/common/tasks/containerd.yaml

- name: Kubeadm, kubelet, kubectl tools installation
  hosts: all
  remote_user: root
  strategy: free
  gather_facts: false
  vars:
    kubernetes_version: "1.30"
  tasks:
    - name: K8s tools installation
      ansible.builtin.include_tasks: roles/common/tasks/k8stools.yaml
