- name: Copy config file
  ansible.builtin.copy:
    src: crictl.yaml
    dest: /etc/crictl.yaml
    mode: '0644'
    owner: 'root'
    group: 'root'

- name: Downloading crictl
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ crictl_version }}/crictl-v{{ crictl_version }}-linux-arm64.tar.gz
    dest: /root/
    mode: '0644'
    owner: 'root'
    group: 'root'

- name: Extract crictl to /usr/bin
  ansible.builtin.unarchive:
    src: /root/crictl-v{{ crictl_version }}-linux-arm64.tar.gz
    dest: /usr/bin
    remote_src: true
    mode: '0755'
    owner: 'root'
    group: 'root'
