apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    limits:
      storage: 10Gi
    requests:
      storage: 5Gi
  storageClassName: longhorn
