apiVersion: v1
kind: Service
metadata:
  labels:
    app: radarr-svc
  name: radarr-svc
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 7878
    nodePort: 30320
  selector:
    app: radarr
  type: NodePort
status:
  loadBalancer: {}
