
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qbittorrent
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - image: lscr.io/linuxserver/qbittorrent:latest
        name: qbittorrent
        ports:
          - name: ui
            containerPort: 8080
          - name: torrent
            containerPort: 6881
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Etc/UTC"
          - name: WEBUI_PORT
            value: "8080"
          - name: TORRENTING_PORT
            value: "6881"
        volumeMounts:
          - name: data
            mountPath: /config
            subPath: qbittorrent/
          - name: data
            mountPath: /downloads
            subPath: downloads/
        resources: {}

      volumes:
        - name: data
          persistentVolumeClaim:
           claimName: radarr-shared-pvc
           readOnly: false
