apiVersion: v1
kind: Service
metadata:
  labels:
    app: qbittorrent
  name: qbittorrent
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30321
  - name: "torrent"
    port: 6881
    protocol: TCP
    targetPort: 6881
  selector:
    app: qbittorrent
  type: NodePort
status:
  loadBalancer: {}
